from vasflam.lib.logging import debug
from vasflam.uoevo.lib.crafting import CRAFTING_GUMP_ID
from vasflam.uoevo.lib.crafting.resources import RESOURCE_COLORS
from vasflam.uoevo.lib.crafting.common import CraftingSection, CraftingConfig, CraftingItem

BS_BOD_COLOR = 0x13E3
BS_TOOL_GRAPHIC = 0x13E3
BS_CRAFTING_SECTIONS = [
    CraftingSection('ringmail', 1, [
        CraftingItem('ringmail gloves', button=2),
        CraftingItem('ringmail leggings', button=9),
        CraftingItem('ringmail sleeves', button=16),
        CraftingItem('ringmail sleeves', button=23),
    ]),
    CraftingSection('chainmail', 8, [
        CraftingItem('chainmail coif', button=2),
        CraftingItem('chainmail leggings', button=9),
        CraftingItem('chainmail tunic', button=16),
    ]),
    CraftingSection('platemail', 15, [
        CraftingItem('platemail arms', button=2),
        CraftingItem('platemail gloves', button=9),
        CraftingItem('platemail gorget', button=16),
        CraftingItem('platemail legs', button=23),
        CraftingItem('platemail tunic', button=30),
        CraftingItem('platemail (female)', button=37),
        CraftingItem('dragon barding deed', button=44),
        CraftingItem('platemail mempo', button=51),
        CraftingItem('platemail do', button=58),
        CraftingItem('platemail hiro sode', button=65),
        CraftingItem('platemail suneate', button=72),
        CraftingItem('platemail haidate', button=79),
        CraftingItem('gargish platemail arms', button=88),
        CraftingItem('gargish platemail chest', button=95),
        CraftingItem('gargish platemail chest', button=102),
        CraftingItem('gargish platemail kilt', button=109),
        CraftingItem('gargish platemail leggings', button=116),
    ]),
    CraftingSection('helmets', 22, [
        CraftingItem('bascinet', button=2),
        CraftingItem('close helmet', button=9),
        CraftingItem('helmet', button=16),
        CraftingItem('norse helm', button=23),
        CraftingItem('plate helm', button=30),
        CraftingItem('chainmail hatsuburi', button=37),
        CraftingItem('platemail hatsuburi', button=44),
        CraftingItem('heavy platemail jingasa', button=51),
        CraftingItem('light platemail jingasa', button=58),
        CraftingItem('platemail hiro sode', button=65),
        CraftingItem('small platemail jingasa', button=72),
        CraftingItem('decorative platemail kabuto', button=79),
        CraftingItem('platemail battle kabuto', button=88),
        CraftingItem('standard platemail kabuto', button=95),
        CraftingItem('circlet', button=102),
        CraftingItem('royal circlet', button=109),
        CraftingItem('gemmed circlet', button=116),
    ]),
    CraftingSection('shields', 29, [
        CraftingItem('buckler', button=2),
        CraftingItem('bronze shield', button=9),
        CraftingItem('heater shield', button=16),
        CraftingItem('metal shield', button=23),
        CraftingItem('metal kite shield', button=30),
        CraftingItem('tear kite shield', button=37),
        CraftingItem('Chaos shield', button=44),
        CraftingItem('Order shield', button=51),
    ]),
    CraftingSection('throwing', 36, [
        CraftingItem('boomerang', button=2),
        CraftingItem('cyclone', button=9),
        CraftingItem('soul glavie', button=16),
    ]),
    CraftingSection('bladed', 43, [
        CraftingItem("bone harvester", button=2),
        CraftingItem("broadsword", button=9),
        CraftingItem("crescent blade", button=16),
        CraftingItem("cutlass", button=23),
        CraftingItem("dagger", button=30),
        CraftingItem("katana", button=37),
        CraftingItem("kryss", button=44),
        CraftingItem("longsword", button=51),
        CraftingItem("scimitar", button=58),
        CraftingItem("viking sword", button=65),
        CraftingItem("no-dachi", button=72),
        CraftingItem("wakizashi", button=79),
        CraftingItem("lajatang", button=86),
        CraftingItem("daisho", button=93),
        CraftingItem("tekagi", button=100),
        CraftingItem("shuriken", button=107),
        CraftingItem("kama", button=114),
        CraftingItem("sai", button=121),
        CraftingItem("radiant scimitar", button=128),
        CraftingItem("war cleaver", button=135),
        CraftingItem("elven spellblade", button=142),
        CraftingItem("assassin spike", button=149),
        CraftingItem("leafblade", button=156),
        CraftingItem("rune blade", button=163),
        CraftingItem("elven machete", button=170),
        CraftingItem("Rune Carving Knife", button=177),
        CraftingItem("Cold Forged Blade", button=184),
        CraftingItem("Overseer Sundered Blade", button=191),
        CraftingItem("Luminous Rune Blade", button=198),
        CraftingItem("true spellblade", button=205),
        CraftingItem("icy spellblade", button=212),
        CraftingItem("fiery spellblade", button=219),
        CraftingItem("spellblade of defense", button=226),
        CraftingItem("true assassin spike", button=233),
        CraftingItem("charged assassin spike", button=240),
        CraftingItem("magekiller assassin spike", button=247),
        CraftingItem("wounding assassin spike", button=254),
        CraftingItem("true leafblade", button=261),
        CraftingItem("luckblade", button=268),
        CraftingItem("magekiller leafblade", button=275),
        CraftingItem("leafblade of ease", button=282),
        CraftingItem("knight's war cleaver", button=289),
        CraftingItem("butcher's war cleaver", button=296),
        CraftingItem("serrated war cleaver", button=303),
        CraftingItem("true war cleaver", button=310),
        CraftingItem("adventurer's machete", button=317),
        CraftingItem("Orcish Machete", button=324),
        CraftingItem("machete of defense", button=331),
        CraftingItem("Diseased Machete", button=338),
        CraftingItem("runesabre", button=345),
        CraftingItem("mage's rune blade", button=352),
        CraftingItem("rune blade of knowledge", button=359),
        CraftingItem("Corrupted Rune Blade", button=366),
        CraftingItem("true radiant scimitar", button=373),
        CraftingItem("darkglow scimitar", button=380),
        CraftingItem("icy scimitar", button=387),
        CraftingItem("twinkling scimitar", button=394),
        CraftingItem("bone machete", button=401),
        CraftingItem("bloodblade", button=408),
        CraftingItem("dread sword", button=415),
        CraftingItem("gargish dagger", button=422),
        CraftingItem("gargish talwar", button=429),
        CraftingItem("shortblade", button=436),
    ]),
    CraftingSection('axes', 50, [
        CraftingItem("axe", button=2),
        CraftingItem("battle axe", button=9),
        CraftingItem("double axe", button=16),
        CraftingItem("executioner's axe", button=23),
        CraftingItem("large battle axe", button=30),
        CraftingItem("two handed axe", button=37),
        CraftingItem("war axe", button=44),
        CraftingItem("ornate axe", button=51),
        CraftingItem("guardian axe", button=58),
        CraftingItem("singing axe", button=65),
        CraftingItem("thundering axe", button=72),
        CraftingItem("heavy ornate axe", button=79),
        CraftingItem("dual short axes", button=86),
    ]),
    CraftingSection('polearms', 57, [
        CraftingItem("bardiche", button=2),
        CraftingItem("bladed staff", button=9),
        CraftingItem("double bladed staff", button=16),
        CraftingItem("halberd", button=23),
        CraftingItem("lance", button=30),
        CraftingItem("pike", button=37),
        CraftingItem("short spear", button=44),
        CraftingItem("scythe", button=51),
        CraftingItem("spear", button=58),
        CraftingItem("war fork", button=65),
        CraftingItem("dual pointed spear", button=72),
    ]),
    CraftingSection('bashing', 64, [
        CraftingItem("hammer pick", button=2),
        CraftingItem("mace", button=9),
        CraftingItem("maul", button=16),
        CraftingItem("scepter", button=23),
        CraftingItem("war mace", button=30),
        CraftingItem("war hammer", button=37),
        CraftingItem("tessen", button=44),
        CraftingItem("diamond mace", button=51),
        CraftingItem("Shard Thrasher", button=58),
        CraftingItem("ruby mace", button=65),
        CraftingItem("emerald mace", button=72),
        CraftingItem("sapphire mace", button=79),
        CraftingItem("silver-etched mace", button=86),
        CraftingItem("disc mace", button=93),
    ]),
    CraftingSection('dragon scale armor', 71, [
        CraftingItem("dragon gloves", button=2),
        CraftingItem("dragon helm", button=9),
        CraftingItem("dragon leggings", button=16),
        CraftingItem("dragon sleeves", button=23),
        CraftingItem("dragon breastplate", button=30),
    ]),
]

def smelt_item(item):
    if Gumps.HasGump(CRAFTING_GUMP_ID):
        gd = Gumps.GetGumpData(CRAFTING_GUMP_ID)
        if 'SMELT ITEM' not in gd.gumpText:
            debug('No smelt item button in gump')
            Gumps.SendAction(CRAFTING_GUMP_ID, 14)
            Target.WaitForTarget(13000)
            Target.TargetExecute(item)
            Gumps.WaitForGump(CRAFTING_GUMP_ID, 13000)
BS_CONFIG = CraftingConfig(BS_BOD_COLOR, BS_TOOL_GRAPHIC, BS_CRAFTING_SECTIONS, RESOURCE_COLORS, recycle_fn=smelt_item)
