from vasflam.uoevo.lib.crafting.common import CraftingSection, CraftingItem, CraftingConfig
from vasflam.uoevo.lib.crafting.resources import RESOURCE_COLORS, ResourceColors, ResourceColor

TAILORING_BOD_COLOR = 0x0483
TAILORING_TOOL_GRAPHIC = 0x0F9D
TAILORING_RESOURCE_COLORS = ResourceColors(7, [
    ResourceColor('default', 0, 6),
    ResourceColor('Leather', 0, 6),
    ResourceColor('Spined', 0x08ac, 13),
    ResourceColor('Horned', 0x0845, 20),
    # ResourceColor('BARBED HIDES', 0x0845, 34),
    ResourceColor('Barbed', 0x0851, 34),

    ResourceColor('Polar', 0x047e, 41),
    ResourceColor('Synthetic', 0x03ff, 48),
    ResourceColor('Blaze', 0x04ec, 55),
    ResourceColor('Daemonic', 0x0020, 62),
    ResourceColor('Shadow', 0x0966, 69),
    ResourceColor('Frost', 0x005d, 76),
    ResourceColor('Ethereal', 0x0487, 83),
])

TAILORING_CRAFTING_SECTIONS = [
    CraftingSection('hats', 1, [
        CraftingItem('skullcap', 2),
        CraftingItem('bandana', 9),
        CraftingItem('floppy hat', 16),
        CraftingItem('cap', 23),
        CraftingItem('wide-brim hat', 30),
        CraftingItem('straw hat', 37),
        CraftingItem('tall straw hat', 44),
        CraftingItem("wizard's hat", 51),
        CraftingItem('bonnet', 58),
        CraftingItem('feathered hat', 65),
        CraftingItem('tricorne hat', 72),
        CraftingItem('jester hat', 79),
        CraftingItem('flower garland', 86),
        CraftingItem('cloth ninja hood', 93),
        CraftingItem('kasa', 100),

    ]),
    CraftingSection('shirts', 8, [
        CraftingItem('doublet', 2),
        CraftingItem('shirt', 9),
        CraftingItem('fancy shirt', 16),
        CraftingItem('tunic', 23),
        CraftingItem('surcoat', 30),
        CraftingItem('plain dress', 37),
        CraftingItem('fancy dress', 44, 0x1F00),
        CraftingItem('cloak', 51),
        CraftingItem('robe', 58),
        CraftingItem('jester suit', 65),
        CraftingItem('fur cape', 72),
        CraftingItem('gilded dress', 79),
        CraftingItem('formal shirt', 86),
        CraftingItem('cloth ninja jacket', 93),
        CraftingItem('kamishimo', 100),
        CraftingItem('hakama-shita', 107),
        CraftingItem('male kimono', 114),
        CraftingItem('female kimono', 121),
        CraftingItem('jin-baori', 128),
        CraftingItem('elven shirt', 135),
        CraftingItem('elven shirt', 142),
        CraftingItem('elven robe', 149),
        CraftingItem('female elven robe', 156),
    ]),
    CraftingSection('pants', 15, [
CraftingItem('short pants', 2),
CraftingItem('long pants', 9),
CraftingItem('kilt', 16),
CraftingItem('skirt', 23),
CraftingItem('fur sarong', 30),
CraftingItem('hakama', 37),
CraftingItem('tattsuke-hakama', 44),
CraftingItem('elven pants', 51),
CraftingItem('woodland belt', 58),
    ]),
    CraftingSection('misc', 22, [
        CraftingItem('Craft Bag', 2),
        CraftingItem('body sash', 9),
        CraftingItem('half apron', 16),
        CraftingItem('full apron', 23),
        CraftingItem('obi', 30),
        CraftingItem('elven quiver', 37),
        CraftingItem('quiver of fire', 44),
        CraftingItem('quiver of ice', 51),
        CraftingItem('Quiver of Blight', 58),
        CraftingItem('Quiver of Lightning', 65),
        CraftingItem('leather container engraving tool', 72),
        CraftingItem('oil cloth', 79),
        CraftingItem('goza (east)', 86),
        CraftingItem('goza (south)', 93),
        CraftingItem('square goza (east)', 100),
        CraftingItem('square goza (south)', 107),
        CraftingItem('brocade goza (east)', 114),
        CraftingItem('brocade goza (south)', 121),
        CraftingItem('square brocade goza (east)', 128),
        CraftingItem('square brocade goza (south)', 135),
        CraftingItem('elven boots', 142),
    ]),
    CraftingSection('footwear', 29, [
        CraftingItem('fur boots', 2),
        CraftingItem('ninja tabi', 9),
        CraftingItem('waraji and tabi', 16),
        CraftingItem('sandals', 23),
        CraftingItem('shoes', 30),
        CraftingItem('boots', 37),
        CraftingItem('thigh boots', 44),
        CraftingItem('Gargish Leather Talons', 51),
    ]),
    CraftingSection('leather armor', 36, [
        CraftingItem('Spell Woven Britches', 2),
        CraftingItem('Song Woven Mantle', 9),
        CraftingItem("Stitcher's Mittens", 16),
        CraftingItem('leather gorget', 23),
        CraftingItem('leather cap', 30),
        CraftingItem('leather gloves', 37),
        CraftingItem('leather sleeves', 44),
        CraftingItem('leather leggings', 51),
        CraftingItem('leather tunic', 58),
        CraftingItem('leather jingasa', 65),
        CraftingItem('leather mempo', 72),
        CraftingItem('leather do', 79),
        CraftingItem('leather hiro sode', 86),
        CraftingItem('leather suneate', 93),
        CraftingItem('leather haidate', 100),
        CraftingItem('leather ninja pants', 107),
        CraftingItem('leather ninja jacket', 114),
        CraftingItem('leather ninja belt', 121),
        CraftingItem('leather ninja mitts', 128),
        CraftingItem('leather ninja hood', 135),
        CraftingItem('gargish leather arms', 142),
        CraftingItem('gargish leather chest', 149),
        CraftingItem('gargish leather kilt', 156),
        CraftingItem('gargish leather leggings', 163),
        CraftingItem('Gargish Leather Wing Armor', 170),
        CraftingItem('leaf tunic', 177),
        CraftingItem('leaf arms', 184),
        CraftingItem('leaf gloves', 191),
        CraftingItem('leaf leggings', 198),
        CraftingItem('leaf gorget', 205),
        CraftingItem('leaf tonlet', 212),
    ]),
    CraftingSection('studded armor', 43, [
        CraftingItem('studded gorget', 2),
        CraftingItem('studded gloves', 9),
        CraftingItem('studded sleeves', 16),
        CraftingItem('studded leggings', 23),
        CraftingItem('studded tunic', 30),
        CraftingItem('studded mempo', 37),
        CraftingItem('studded do', 44),
        CraftingItem('studded hiro sode', 51),
        CraftingItem('studded suneate', 58),
        CraftingItem('studded haidate', 65),
        CraftingItem('hide tunic', 72),
        CraftingItem('hide pauldrons', 79),
        CraftingItem('hide gloves', 86),
        CraftingItem('hide pants', 93),
        CraftingItem('hide gorget', 100),
    ]),
    CraftingSection('female armor', 50, [
        CraftingItem('leather shorts', 2),
        CraftingItem('leather skirt', 9),
        CraftingItem('leather bustier', 16),
        CraftingItem('studded bustier', 23),
        CraftingItem('female leather armor', 30),
        CraftingItem('studded armor', 37),
    ]),
    CraftingSection('bone armor', 57, [
        CraftingItem('bone helmet', 2),
        CraftingItem('bone gloves', 9),
        CraftingItem('bone arms', 16),
        CraftingItem('bone leggings', 23),
        CraftingItem('bone armor', 30),
    ]),
    CraftingSection('cloth armor', 64, [
        CraftingItem('gargish cloth arms', 2),
        CraftingItem('gargish cloth chest', 9),
        CraftingItem('gargish cloth kilt', 16),
        CraftingItem('gargish cloth leggings', 23),
        CraftingItem('Gargish Cloth Wing Armor', 30),
        CraftingItem('Britannia Dragon Cloak', 37),
        CraftingItem('Belt of Tokuno', 44),
        CraftingItem('Sash of The Pit', 51),
    ]),
]

def cut_item(item):
    graphic = 0x0F9F
    scissors = Items.FindByID(graphic, 0, Player.Backpack.Serial, 2)
    if scissors:
        Items.UseItem(scissors)
        Target.WaitForTarget(13000)
        Target.TargetExecute(item)

TAILORING_CONFIG = CraftingConfig(TAILORING_BOD_COLOR, TAILORING_TOOL_GRAPHIC, TAILORING_CRAFTING_SECTIONS, TAILORING_RESOURCE_COLORS, recycle_fn=cut_item)