from vasflam.uoevo.lib.crafting import TINKERING_BOD_GUMP_ID
from vasflam.uoevo.lib.crafting.common import CraftingSection, CraftingConfig, CraftingItem
from vasflam.uoevo.lib.crafting.resources import RESOURCE_COLORS, TINKERING_RESOURCE_COLORS

TINKERING_BOD_COLOR = 0x0014
TINKERING_TOOL_GRAPHIC = 0x1EB8

TINKERING_CRAFTING_SECTIONS = [
    CraftingSection('wooden items', 1, [
        CraftingItem('jointing plane', 2),
        CraftingItem('moulding planes', 9),
        CraftingItem('smoothing plane', 16),
        CraftingItem('clock frame', 23),
        CraftingItem('axle', 30),
        CraftingItem('rolling pin', 37),
        CraftingItem('nunchaku', 44),
    ]),
    CraftingSection('tools', 8, [
        CraftingItem('scissors', 2),
        CraftingItem('mortar and pestle', 9),
        CraftingItem('scorp', 16),
        CraftingItem('tinker\'s tools', 23),
        CraftingItem('hatchet', 30),
        CraftingItem('draw knife', 37),
        CraftingItem('sewing kit', 44),
        CraftingItem('saw', 51),
        CraftingItem('dovetail saw', 58),
        CraftingItem('froe', 65),
        CraftingItem('shovel', 72),
        CraftingItem('hammer', 79),
        CraftingItem('tongs', 86),
        CraftingItem('smith\'s hammer', 93),
        CraftingItem('sledge hammer', 100),
        CraftingItem('inshave', 107),
        CraftingItem('pickaxe', 114),
        CraftingItem('lockpick', 121),
        CraftingItem('skillet', 128, graphic=2431),
        CraftingItem('frypan', 128, graphic=2431), # temporary, name in BOD is frypan, but in craft skillet
        CraftingItem('flour sifter', 135),
        CraftingItem('fletcher\'s tools', 142),
        CraftingItem('mapmaker\'s pen', 149),
        CraftingItem('scribe\'s pen', 156),
        CraftingItem('metal container engraving tool', 163),
    ]),
    CraftingSection('parts', 15, [
        CraftingItem('gears', 2),
        CraftingItem('clock parts', 9),
        CraftingItem('barrel tap', 16),
        CraftingItem('springs', 23),
        CraftingItem('sextant parts', 30),
        CraftingItem('barrel hoops', 37),
        CraftingItem('hinge', 44),
        CraftingItem('bola balls', 51),
        CraftingItem('jeweled filigree', 58),
    ]),
    CraftingSection('untensils', 22, [
        CraftingItem('butcher knife', 2),
        CraftingItem('spoon (left)', 9),
        CraftingItem('spoon (right)', 16),
        CraftingItem('plate', 23),
        CraftingItem('fork (left)', 30),
        CraftingItem('fork (right)', 37),
        CraftingItem('cleaver', 44),
        CraftingItem('knife (left)', 51),
        CraftingItem('knife (right)', 58),
        CraftingItem('goblet', 65),
        CraftingItem('pewter mug', 72),
        CraftingItem('skinning knife', 79),
    ]),
    CraftingSection('miscelleaneous', 29, [
        CraftingItem('key ring', 2),
        CraftingItem('candelabra', 9),
        CraftingItem('scales', 16),
        CraftingItem('iron key', 23),
        CraftingItem('globe', 30),
        CraftingItem('spyglass', 37),
        CraftingItem('lantern', 44),
        CraftingItem('heating stand', 51),
        CraftingItem('shoji lantern', 58),
        CraftingItem('paper lantern', 65),
        CraftingItem('round paper lantern', 72),
        CraftingItem('wind chimes', 79),
        CraftingItem('fancy wind chimes', 86),
    ]),
    CraftingSection('jewelry', 36, [
        CraftingItem('star sapphire ring', 2),
        CraftingItem('star sapphire necklace (silver)', 9),
        CraftingItem('star sapphire necklace (jewelled)', 16),
        CraftingItem('star sapphire earrings', 23),
        CraftingItem('star sapphire necklace (golden)', 30),
        CraftingItem('star sapphire bracelet', 37),
        CraftingItem('emerald ring', 44),
        CraftingItem('emerald necklace (silver)', 51),
        CraftingItem('emerald necklace (jewelled)', 58),
        CraftingItem('emerald earrings', 65),
        CraftingItem('emerald necklace (golden)', 72),
        CraftingItem('emerald bracelet', 79),
        CraftingItem('sapphire ring', 86),
        CraftingItem('sapphire necklace (silver)', 93),
        CraftingItem('sapphire necklace (jewelled)', 100),
        CraftingItem('sapphire earrings', 107),
        CraftingItem('sapphire necklace (golden)', 114),
        CraftingItem('sapphire bracelet', 121),
        CraftingItem('ruby ring', 128),
        CraftingItem('ruby necklace (silver)', 135),
        CraftingItem('ruby necklace (jewelled)', 142),
        CraftingItem('ruby earrings', 149),
        CraftingItem('ruby necklace (golden)', 156),
        CraftingItem('ruby bracelet', 163),
        CraftingItem('citrine ring', 170),
        CraftingItem('citrine necklace (silver)', 177),
        CraftingItem('citrine necklace (jewelled)', 184),
        CraftingItem('citrine earrings', 191),
        CraftingItem('citrine necklace (golden)', 198),
        CraftingItem('citrine bracelet', 205),
        CraftingItem('amethyst ring', 212),
        CraftingItem('amethyst necklace (silver)', 219),
        CraftingItem('amethyst necklace (jewelled)', 226),
        CraftingItem('amethyst earrings', 233),
        CraftingItem('amethyst necklace (golden)', 240),
        CraftingItem('amethyst bracelet', 247),
        CraftingItem('tourmaline ring', 254),
        CraftingItem('tourmaline necklace (silver)', 261),
        CraftingItem('tourmaline necklace (jewelled)', 268),
        CraftingItem('tourmaline earrings', 275),
        CraftingItem('tourmaline necklace (golden)', 282),
        CraftingItem('tourmaline bracelet', 289),
        CraftingItem('amber ring', 296),
        CraftingItem('amber necklace (silver)', 303),
        CraftingItem('amber necklace (jewelled)', 310),
        CraftingItem('amber earrings', 317),
        CraftingItem('amber necklace (golden)', 324),
        CraftingItem('amber bracelet', 331),
        CraftingItem('diamond ring', 338),
        CraftingItem('diamond necklace (silver)', 345),
        CraftingItem('diamond necklace (jewelled)', 352),
        CraftingItem('diamond earrings', 359),
        CraftingItem('diamond necklace (golden)', 366),
        CraftingItem('diamond bracelet', 373),
    ]),
    CraftingSection('asemblies', 43, [
        CraftingItem('axle with gears', 2),
        CraftingItem('clock parts', 9),
        CraftingItem('sextant parts', 16),
        CraftingItem('clock (right)', 23),
        CraftingItem('clock (left)', 30),
        CraftingItem('sextant', 37),
        CraftingItem('bola', 44),
        CraftingItem('potion keg', 51),
        CraftingItem('hitching rope', 58),
        CraftingItem('hitching post (replica)', 65),
    ]),
    CraftingSection('traps', 50, [
        CraftingItem('dart trap', 2),
        CraftingItem('poison trap', 9),
        CraftingItem('explosion trap', 16),
        CraftingItem('faction gas trap', 23),
        CraftingItem('faction explosion trap', 30),
        CraftingItem('faction saw trap', 37),
        CraftingItem('faction spike trap', 44),
        CraftingItem('faction trap removal kit', 51),
    ]),
    CraftingSection('customs', 57, [
        CraftingItem('Reagent Axe', 2),
        CraftingItem('Gold Pan', 9),
        CraftingItem('Pyro Technic Kit', 16),
        CraftingItem('Iron Clockwork Assembly', 23),
        CraftingItem('Emperor\'s Seal: Orange', 30),
        CraftingItem('Emperor\'s Seal: Green', 37),
        CraftingItem('Emperor\'s Seal: Blue', 44),
        CraftingItem('Emperor\'s Seal: Red', 51),
        CraftingItem('Emperor\'s Seal: Purple', 58),
        CraftingItem('Emperor\'s Seal: Brown', 65),
        CraftingItem('Emperor\'s Seal: Black', 72),
        CraftingItem('Lockbox Key', 79),
        CraftingItem('Lockbox Brush', 86),
        CraftingItem('Gray Mouser\'s Toolkit', 93),
        CraftingItem('Gold Lined Powder Vial', 100),
        CraftingItem('Vial of the Shattered Arcane', 107),
        CraftingItem('Alchemy Powder Vial', 114),
        CraftingItem('Powder Grinder', 121),
        CraftingItem('Artifact Grinder', 128),
    ]),
    CraftingSection('magic jewelry', 64, [
        CraftingItem('brilliant amber bracelet', 2),
        CraftingItem('fire ruby bracelet', 9),
        CraftingItem('dark sapphire bracelet', 16),
        CraftingItem('white pearl bracelet', 23),
        CraftingItem('ecru citrine ring', 30),
        CraftingItem('blue diamond ring', 37),
        CraftingItem('perfect emerald ring', 44),
        CraftingItem('turquoise ring', 51),
        CraftingItem('Resilient Bracer', 58),
        CraftingItem('Essence of Battle', 65),
        CraftingItem('Pendant of the Magi', 72),
    ]),
]

TINKERING_CONFIG = CraftingConfig(
    TINKERING_BOD_COLOR,
    TINKERING_TOOL_GRAPHIC,
    TINKERING_CRAFTING_SECTIONS,
    TINKERING_RESOURCE_COLORS,
    bod_gump_id=TINKERING_BOD_GUMP_ID
)